#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-notebook_shim
Version  : 0.2.3
Release  : 15
URL      : https://files.pythonhosted.org/packages/ea/10/6c6c7adc0d61e72cfc4055d0671bbd12bdc6ffea86892e903bd2398b9019/notebook_shim-0.2.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/ea/10/6c6c7adc0d61e72cfc4055d0671bbd12bdc6ffea86892e903bd2398b9019/notebook_shim-0.2.3.tar.gz
Summary  : A shim layer for notebook traits and config
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-notebook_shim-data = %{version}-%{release}
Requires: pypi-notebook_shim-license = %{version}-%{release}
Requires: pypi-notebook_shim-python = %{version}-%{release}
Requires: pypi-notebook_shim-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(hatchling)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Notebook Shim
This project provides a way for JupyterLab and other frontends to switch to [Jupyter Server](https://github.com/jupyter/jupyter_server/) for their Python Web application backend.

%package data
Summary: data components for the pypi-notebook_shim package.
Group: Data

%description data
data components for the pypi-notebook_shim package.


%package license
Summary: license components for the pypi-notebook_shim package.
Group: Default

%description license
license components for the pypi-notebook_shim package.


%package python
Summary: python components for the pypi-notebook_shim package.
Group: Default
Requires: pypi-notebook_shim-python3 = %{version}-%{release}

%description python
python components for the pypi-notebook_shim package.


%package python3
Summary: python3 components for the pypi-notebook_shim package.
Group: Default
Requires: python3-core
Provides: pypi(notebook_shim)
Requires: pypi(jupyter_server)

%description python3
python3 components for the pypi-notebook_shim package.


%prep
%setup -q -n notebook_shim-0.2.3
cd %{_builddir}/notebook_shim-0.2.3
pushd ..
cp -a notebook_shim-0.2.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1682608993
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-notebook_shim
cp %{_builddir}/notebook_shim-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-notebook_shim/2a50ebddb1cde7ca498946ed224569fe7408d389 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
## install_append content
mkdir -p %{buildroot}/usr/share/jupyter
mv %{buildroot}/usr/etc/  %{buildroot}/usr/share/
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/etc/jupyter/jupyter_server_config.d/notebook_shim.json

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-notebook_shim/2a50ebddb1cde7ca498946ed224569fe7408d389

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
